services:
  - type: web
    name: resume-analyzer-backend
    env: python
    runtime: python-3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    envVars:
      - key: PORT
        value: 10000